"""create aluno_materia association

Revision ID: fb0a11c3fd92
Revises: b14b23af8c99
Create Date: 2026-05-22 14:00:00.496150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0a11c3fd92'
down_revision: Union[str, Sequence[str], None] = 'b14b23af8c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno_materia',
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aluno_id', 'materia_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluno_materia')
    # ### end Alembic commands ###
